on food bar change:
  cancel event
on death of player:
  if attacker is a player:
    broadcast "&c☠ %victim% &7was defeated by &a🗡 %attacker% &7(&c%attacker's health * 2%❤&7)"
on respawn:
  give player feather named "&aQuick Respawn"
on rightclick with feather:
  if name of player's tool is "&aQuick Respawn":
    clear player's inventory
    console command "/tp %player% 0 64 0"
    console command "/kit give Sword %player%"
